services:
  postgres:
    image: postgres:18.0-alpine
    container_name: finhub_postgres
    env_file: config/localhost.env
    ports:
      - "5432:5432"
    volumes:
      - finhub_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USERNAME"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  finhub_pg_data: